const START_GAME = 'START_GAME';
const MOVE_UP = 'MOVE_UP';
const MOVE_BOTTOM = 'MOVE_BOTTOM';
const MOVE_LEFT = 'MOVE_LEFT';
const MOVE_RIGHT = 'MOVE_RIGHT';
const PLACE_RANDOM = 'PLACE_RANDOM';

export {
  START_GAME,
  MOVE_UP,
  MOVE_BOTTOM,
  MOVE_LEFT,
  MOVE_RIGHT,
  PLACE_RANDOM
}